FORMATTED_TOP_THREE_ARTICLES = {}

TOP_ARTICLES_RESPONSE = {'status': 'ok', 'totalResults': 3, 'articles': [{'source': {'id': 'crypto-coins-news', 'name': 'Crypto Coins News'}, 'author': None, 'title': 'Bitcoin Investor Sues AT&T for $224 Million after Mobile-Linked Theft', 'description': 'A bitcoin investor has sued AT&T for $224 million after losing millions in a cryptocurrency theft that he says is the cell phone provider’s fault.', 'url': 'https://www.ccn.com/bitcoin-investor-sues-att-for-224-million-after-mobile-linked-theft/', 'urlToImage': 'https://www.ccn.com/wp-content/uploads/2018/08/att-cryptocurrency-bitcoin-blockchain.jpg', 'publishedAt': '2018-08-15T20:40:33Z'}, {'source': {'id': 'crypto-coins-news', 'name': 'Crypto Coins News'}, 'author': None, 'title': 'Bitcoin Price Intraday Analysis: BTCUSD Recovers on Weak Upside Promise', 'description': 'The Bitcoin market on Wednesday attempted a decent bullish recovery, extending the recent marginal gains to an impressive 10% upside from the previous lows.', 'url': 'https://www.ccn.com/bitcoin-price-intraday-analysis-btcusd-recovers-on-weak-upside-promise/', 'urlToImage': 'https://www.ccn.com/wp-content/uploads/2018/07/bitcoin-price-brian-kelly.jpg', 'publishedAt': '2018-08-15T16:38:45Z'}, {'source': {'id': 'crypto-coins-news', 'name': 'Crypto Coins News'}, 'author': None, 'title': 'Bitcoin and Ethereum Rise 6% as Market Rebounds During Dark Skies', 'description': 'Bitcoin and Ethereum have risen by more than 6 percent in value, but some analysts are still not convinced about the short-term trend of the crypto market.', 'url': 'https://www.ccn.com/bitcoin-and-ethereum-rise-6-as-market-rebounds-during-dark-skies/', 'urlToImage': 'https://www.ccn.com/wp-content/uploads/2017/12/Bitcoin-chart-bounce.jpg', 'publishedAt': '2018-08-15T11:19:13Z'}]}
{'title': 'Bitcoin and Ethereum Rise 6% as Market Rebounds During Dark Skies', 'url': 'https://www.ccn.com/bitcoin-and-ethereum-rise-6-as-market-rebounds-during-dark-skies/'}

TOP_ARTICLES = TOP_ARTICLES_RESPONSE['articles']

TOP_ARTICLE = {'source': {'id': 'crypto-coins-news', 'name': 'Crypto Coins News'}, 'author': None, 'title': 'Bitcoin Price Intraday Analysis: BTCUSD Recovers on Weak Upside Promise', 'description': 'The Bitcoin market on Wednesday attempted a decent bullish recovery, extending the recent marginal gains to an impressive 10% upside from the previous lows.', 'url': 'https://www.ccn.com/bitcoin-price-intraday-analysis-btcusd-recovers-on-weak-upside-promise/', 'urlToImage': 'https://www.ccn.com/wp-content/uploads/2018/07/bitcoin-price-brian-kelly.jpg', 'publishedAt': '2018-08-15T16:38:45Z'}

TITLE_AND_URL = {'title': 'Bitcoin Price Intraday Analysis: BTCUSD Recovers on Weak Upside Promise', 'url': 'https://www.ccn.com/bitcoin-price-intraday-analysis-btcusd-recovers-on-weak-upside-promise/'}

STOP_WORDS = ['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's', 't', 'can', 'will', 'just', 'don', "don't", 'should', "should've", 'now', 'd', 'll', 'm', 'o', 're', 've', 'y', 'ain', 'aren', "aren't", 'couldn', "couldn't", 'didn', "didn't", 'doesn', "doesn't", 'hadn', "hadn't", 'hasn', "hasn't", 'haven', "haven't", 'isn', "isn't", 'ma', 'mightn', "mightn't", 'mustn', "mustn't", 'needn', "needn't", 'shan', "shan't", 'shouldn', "shouldn't", 'wasn', "wasn't", 'weren', "weren't", 'won', "won't", 'wouldn', "wouldn't"]

#TOP_THREE_WORDS = {'apple': [4, .31], 'orange': [4, .31], 'bag': [3, .23]}
TOP_THREE_WORDS = {'apple': {'occurences': 4, 'percentage': .31}, 'orange': {'occurences': 4, 'percentage': .31}, 'bag': {'occurences': 3, 'percentage': .23} }
